<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "[[category]]" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package Unika DMS
 * @author Serban George Cristian <business@unikainfocom.in> 
 * @link http://www.unikainfocom.in/
 * @copyright 2013-2017 Unika DMS (http://www.unikainfocom.in/)
 * @license http://www.unikainfocom.in/support
 * @since 1.1
 */
 
 